### ISSUE TITLE
add support gradient

### ISSUE THREAD

**Issue by bmx666** [seanghay/vector-drawable-svg#5]
Hi @seanghay, is it possible to add gradient into project?

I tried to covert this [drawable](https://github.com/ditek/MidiSheetMusic-Android/blob/master/app/src/main/res/drawable-v24/ic_launcher_foreground.xml) into SVG, but vd2svg doesn't support gradient 😔

**Comment by seanghay** [comment]
Hi @bmx666! Right now this lib doesn't support gradients however you can open a pull request for that feature if you don't mind. I will merge that as soon as possible. Thanks.

**Comment by seanghay** [comment]
Thank you!
https://github.com/seanghay/vector-drawable-svg/pull/6
